modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/zaafonin/vs_oddities/issues"
license = "MIT"

[[mods]]
modId = "vs_oddities"
version = "${version}"
displayName = "VS Oddities"
displayURL = "https://github.com/zaafonin/vs_oddities"
authors = "zaafonin"
description = '''
Minor fixes, mod integration and QoL features for Valkyrien Skies 2.
'''
logoFile = "logo.png"

[[dependencies.vs_oddities]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_oddities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_oddities]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_oddities]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.1.3-beta.1,)"
ordering = "AFTER"
side = "BOTH"
